package org.es.tomas.pedra_paper_tisores.Model.Enums

enum class Names {
    ADAM, ADRIAN, ALICE, AMANDA, AMY,
    ANDREW, ANGELA, ARTHUR, AUSTIN, BEATRICE,
    BENJAMIN, CATHERINE, CHARLES, CHLOE, CONNOR,
    DANIEL, DAVID, DIANA, DOROTHY, EDWARD,
    ELIZABETH, ELLIOT, EMILY, ETHAN, FELICITY,
    FIONA, GEORGE, GRACE, HANNAH, HAROLD,
    ISAAC, ISABELLA, JACK, JACOB, JESSICA,
    JOSEPH, JULIA, KEVIN, LAURA, LAWRENCE,
    MARCUS, MARGARET, MATTHEW, NAOMI, NATHAN,
    OLIVER, OLIVIA, PENELOPE, QUENTIN, RACHEL
}